id: IC14CC270
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-10T08:53:36+00:00'
last_modified: '2022-06-15T14:08:41.643555+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3877
  title: འཇམ་དཔལ་ཡེ་ཤེས་གྲུབ་པའི་རྣམ་ཐར་རགས་ཙམ་སྐྱབས་མགོན་ཉིད་ཀྱི་གསུང་ངོ་མ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    37AA:
      image_group_id: I1KG3957
      title: Volume 1 of 'jam dpal ye shes grub pa'i rnam thar rags tsam skyabs mgon
        nyid kyi gsung ngo ma
      total_pages: 62
      order: 1
      base_file: 37AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
